In [1]:
import numpy as np

In [1]:
v1=[]
for i in range(4):
    v2=np.random.randint(0,100,1+i)
    print(v2)
    v1.append(np.array(v2).reshape(-1,1))
v1=np.vstack(v1)
print("vstack",v1)
print("shape",v1.shape)


NameError: name 'np' is not defined

In [6]:
preds=np.random.randint(0,4,100)
outputs=np.random.randint(0,4,100)
acc=np.array(preds==outputs).sum()/len(preds)
print(acc)

0.27


In [5]:
d=np.random.randint(0,5,(20,6))
c=np.random.randint(0,5,(20,2))
f=np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis=1, arr=d)
print(d,f)

[[4 3 3 4 4 1]
 [4 4 0 0 4 2]
 [3 2 0 3 1 2]
 [4 2 3 1 0 0]
 [4 2 0 2 3 3]
 [0 2 2 1 1 3]
 [0 0 0 4 3 3]
 [2 3 1 0 2 1]
 [4 1 1 1 3 4]
 [2 0 0 2 3 2]
 [0 3 1 3 4 4]
 [3 1 3 4 0 0]
 [3 3 1 2 3 3]
 [3 2 2 3 2 1]
 [3 2 3 2 3 2]
 [1 2 2 0 2 2]
 [0 4 3 1 1 4]
 [3 3 1 3 3 3]
 [0 4 4 3 1 2]
 [1 2 3 0 0 3]] [4 4 2 0 2 1 0 1 1 2 3 0 3 2 2 2 1 3 4 0]


In [14]:
a=np.random.randint(0,10,10)
b=np.random.randint(0,10,10)
c=np.random.randint(0,10,10)

print(np.concatenate((a.reshape(-1,1),b.reshape(-1,1),c.reshape(-1,1)),axis=1))


[[9 0 7]
 [0 2 2]
 [7 0 2]
 [4 0 3]
 [8 1 9]
 [7 0 9]
 [6 4 3]
 [1 9 1]
 [6 4 9]
 [8 7 4]]


In [2]:
import torch
import torch.nn as nn
import torchvision
import efficientnet_pytorch
import torchvision.models as models

In [3]:
subject = 'H2'
main_path = os.path.join("E:\\kaggle_imgs", subject)
img_path = os.path.join(main_path, "images")
data_path = os.path.join(main_path, "Data")
save_path = os.path.join(main_path, "saved_models")
best_path = save_path+"/200712.bin"

In [4]:
class Resnext50_32x4d(nn.Module):
    def __init__(self):
        super(Resnext50_32x4d,self).__init__()
        self.base_model=torchvision.models.resnext50_32x4d(pretrained=True)
        num=self.base_model.fc.in_features
        self.base_model.fc=nn.Linear(num,4,bias=True)
    def forward(self,image,targets):
        out=self.base_model(image)
        loss= nn.CrossEntropyLoss()(out,targets)
        return out,loss

In [6]:
model=torchvision.models.resnext50_32x4d(pretrained=True)
num=model.fc.in_features
model.fc=nn.Linear(num,4,bias=True)
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)

In [7]:
output=traced_script_module(torch.ones(1,3,224,224))
print(output[0,:5])

tensor([ 0.3009,  0.0319, -0.1869,  0.0048], grad_fn=<SliceBackward>)


In [25]:
path=save_path+"/traced_resnext50_model.pt"
traced_script_module.save(path)

In [ ]:
traced_script_module.save(save_path+"/traced_resnet_model.pt")
